import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

interface AlertEmailData {
  accountAlerts: Array<{
    email: string;
    score: number;
    previousScore?: number;
  }>;
  domainAlerts: Array<{
    domain: string;
    averageScore: number;
    accountCount: number;
  }>;
  timestamp: string;
}

export async function sendAlertEmail(data: AlertEmailData): Promise<boolean> {
  const alertEmail = process.env.ALERT_EMAIL || 'benreeder@builderbenai.com';

  const accountSection = data.accountAlerts.length > 0
    ? `
      <h2 style="color: #ef4444; margin-top: 24px;">Email Accounts Below Threshold</h2>
      <table style="width: 100%; border-collapse: collapse; margin-top: 12px;">
        <thead>
          <tr style="background: #1f2937;">
            <th style="padding: 12px; text-align: left; border-bottom: 1px solid #374151; color: #f3f4f6;">Email</th>
            <th style="padding: 12px; text-align: left; border-bottom: 1px solid #374151; color: #f3f4f6;">Current Score</th>
            <th style="padding: 12px; text-align: left; border-bottom: 1px solid #374151; color: #f3f4f6;">Previous Score</th>
          </tr>
        </thead>
        <tbody>
          ${data.accountAlerts.map(a => `
            <tr style="background: #111827;">
              <td style="padding: 12px; border-bottom: 1px solid #374151; color: #f3f4f6;">${a.email}</td>
              <td style="padding: 12px; border-bottom: 1px solid #374151; color: ${a.score < 90 ? '#ef4444' : '#eab308'};">${a.score}%</td>
              <td style="padding: 12px; border-bottom: 1px solid #374151; color: #9ca3af;">${a.previousScore !== undefined ? `${a.previousScore}%` : 'N/A'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    `
    : '';

  const domainSection = data.domainAlerts.length > 0
    ? `
      <h2 style="color: #ef4444; margin-top: 24px;">Domains Below Threshold</h2>
      <table style="width: 100%; border-collapse: collapse; margin-top: 12px;">
        <thead>
          <tr style="background: #1f2937;">
            <th style="padding: 12px; text-align: left; border-bottom: 1px solid #374151; color: #f3f4f6;">Domain</th>
            <th style="padding: 12px; text-align: left; border-bottom: 1px solid #374151; color: #f3f4f6;">Average Score</th>
            <th style="padding: 12px; text-align: left; border-bottom: 1px solid #374151; color: #f3f4f6;">Account Count</th>
          </tr>
        </thead>
        <tbody>
          ${data.domainAlerts.map(d => `
            <tr style="background: #111827;">
              <td style="padding: 12px; border-bottom: 1px solid #374151; color: #f3f4f6;">${d.domain}</td>
              <td style="padding: 12px; border-bottom: 1px solid #374151; color: ${d.averageScore < 90 ? '#ef4444' : '#eab308'};">${d.averageScore.toFixed(1)}%</td>
              <td style="padding: 12px; border-bottom: 1px solid #374151; color: #9ca3af;">${d.accountCount}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    `
    : '';

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
      </head>
      <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #111827; color: #f3f4f6; padding: 24px; margin: 0;">
        <div style="max-width: 600px; margin: 0 auto; background: #1f2937; border-radius: 12px; padding: 24px; border: 1px solid #374151;">
          <h1 style="color: #f3f4f6; margin: 0 0 8px 0;">Email Warmup Health Alert</h1>
          <p style="color: #9ca3af; margin: 0 0 24px 0;">
            Detected at: ${data.timestamp}
          </p>

          ${accountSection}
          ${domainSection}

          <div style="margin-top: 24px; padding-top: 24px; border-top: 1px solid #374151;">
            <p style="color: #9ca3af; margin: 0; font-size: 14px;">
              This alert was generated by your Email Health Dashboard.
              Accounts/domains with scores below 97% require attention.
            </p>
          </div>
        </div>
      </body>
    </html>
  `;

  try {
    const { error } = await resend.emails.send({
      from: 'Email Health <benreeder@builderbenai.com>',
      to: 'benreeder@builderbenai.com',
      subject: `Email Warmup Alert: ${data.accountAlerts.length} accounts, ${data.domainAlerts.length} domains below threshold`,
      html,
    });

    if (error) {
      console.error('Failed to send alert email:', error);
      return false;
    }

    return true;
  } catch (error) {
    console.error('Error sending alert email:', error);
    return false;
  }
}
